### PR TITLE
Use react lib v2

### PR DESCRIPTION
**Pull request by tomdixon**
Tested locally with `npx create-react-app template-test --template "file:../cra-template-cogs-client"`

### CODE REVIEW

**Comment by chetbox** [comment]
Was there a change to the Typescript version that should be included here?

**Comment by tomdixon** [comment]
> Was there a change to the Typescript version that should be included here?

Good catch! That's fixed and pushed

**Comment by chetbox** [comment]
`create-react-app` is not happy with Typescript 5 out of the box:

```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR! 
npm ERR! While resolving: react-scripts@5.0.1
npm ERR! Found: typescript@5.3.3
npm ERR! node_modules/typescript
npm ERR!   peer typescript@">= 2.7" from fork-ts-checker-webpack-plugin@6.5.3
npm ERR!   node_modules/fork-ts-checker-webpack-plugin
npm ERR!     fork-ts-checker-webpack-plugin@"^6.5.0" from react-dev-utils@12.0.1
npm ERR!     node_modules/react-dev-utils
npm ERR!       react-dev-utils@"^12.0.1" from react-scripts@5.0.1
npm ERR!       node_modules/react-scripts
npm ERR!         react-scripts@"5.0.1" from the root project
npm ERR!   peer typescript@">=2.8.0 || >= 3.2.0-dev || >= 3.3.0-dev || >= 3.4.0-dev || >= 3.5.0-dev || >= 3.6.0-dev || >= 3.6.0-beta || >= 3.7.0-dev || >= 3.7.0-beta" from tsutils@3.21.0
npm ERR!   node_modules/tsutils
npm ERR!     tsutils@"^3.21.0" from @typescript-eslint/eslint-plugin@5.62.0
npm ERR!     node_modules/@typescript-eslint/eslint-plugin
npm ERR!       @typescript-eslint/eslint-plugin@"^5.5.0" from eslint-config-react-app@7.0.1
npm ERR!       node_modules/eslint-config-react-app
npm ERR!         eslint-config-react-app@"^7.0.1" from react-scripts@5.0.1
npm ERR!         node_modules/react-scripts
npm ERR!       1 more (eslint-plugin-jest)
npm ERR!     tsutils@"^3.21.0" from @typescript-eslint/type-utils@5.62.0
npm ERR!     node_modules/@typescript-eslint/type-utils
npm ERR!       @typescript-eslint/type-utils@"5.62.0" from @typescript-eslint/eslint-plugin@5.62.0
npm ERR!       node_modules/@typescript-eslint/eslint-plugin
npm ERR!         @typescript-eslint/eslint-plugin@"^5.5.0" from eslint-config-react-app@7.0.1
npm ERR!         node_modules/eslint-config-react-app
npm ERR!         1 more (eslint-plugin-jest)
npm ERR!     1 more (@typescript-eslint/typescript-estree)
npm ERR!   1 more (the root project)
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peerOptional typescript@"^3.2.1 || ^4" from react-scripts@5.0.1
npm ERR! node_modules/react-scripts
npm ERR!   react-scripts@"5.0.1" from the root project
npm ERR! 
npm ERR! Conflicting peer dependency: typescript@4.9.5
npm ERR! node_modules/typescript
npm ERR!   peerOptional typescript@"^3.2.1 || ^4" from react-scripts@5.0.1
npm ERR!   node_modules/react-scripts
npm ERR!     react-scripts@"5.0.1" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! 
npm ERR! For a full report see:
npm ERR! /Users/chetan/.npm/_logs/2024-01-19T11_17_58_177Z-eresolve-report.txt

npm ERR! A complete log of this run can be found in: /Users/chetan/.npm/_logs/2024-01-19T11_17_58_177Z-debug-0.log
`npm install --no-audit --save @clockworkdog/cogs-client-react@2 @types/react@18 @types/react-dom@18 @types/node@14 @types/canvas-confetti@^1.6.0 canvas-confetti@^1.6.0 cross-env@7 typescript@5` failed
```

This thread covers some workarounds: https://github.com/facebook/create-react-app/issues/13080

**Comment by chetbox** [comment]
Hilariously I don't get any problems with Typescript 4...!

**Comment by tomdixon** [comment]
> Hilariously I don't get any problems with Typescript 4...!

erk that'll teach me for not retrying after updating. I'll take a look!

**Comment by tomdixon** [comment]
@chetbox Added a workaround which seems to do the job for me. Can you check on your side too?

**Comment by chetbox** [comment]
Works great!

**Pull request merged**
